### ISSUE TITLE
Invalid globals config provided in README

### ISSUE THREAD

**Issue by garg3133** [reallymello/nightwatch-axe-verbose#13]
The globals config provided in the [Global Configuration](https://github.com/reallymello/nightwatch-axe-verbose#global-configuration) section of the README is wrong since `axeSettings.context` can only take a string value (which should be a valid CSS selector) and not an object.

**Comment by reallymello** [comment]
It seems to work with the tests in this repository such as `Will use selector context from test instead of globals`...what are you seeing?  The axe documentation says it can be passed in as objects or css selectors

https://www.deque.com/axe/core-documentation/api-documentation/#api-name-axeconfigure
```
Context Parameter
By default, axe.run will test the entire document. The context object is an optional parameter that can be used to specify which element should and which should not be tested. It can be passed one of the following:

An element reference that represents the portion of the document that must be analyzed
Example: To limit analysis to the <div id="content"> element: document.getElementById("content")
A NodeList such as returned by document.querySelectorAll.
A [CSS selector](https://github.com/dequelabs/axe-core/blob/master/doc/developer-guide.md#supported-css-selectors) that selects the portion(s) of the document that must be analyzed.
An object with exclude and/or include properties
An object with a fromFrames property
An object with a fromShadowDom property
```

**Comment by garg3133** [comment]
>  seems to work with the tests in this repository such as `Will use selector context from test instead of globals`

But you have not set `context` as an object anywhere in the tests, it's always a string.

> what are you seeing

Passing an object as `context` would give error, since [`document.querySelector()`](https://github.com/reallymello/nightwatch-axe-verbose/blob/535be8273828b3cf56ca759e012a8d6fde81500d/nightwatch/commands/_axeInjectFunc.js#L9) can only take a string as the argument.
![image](https://user-images.githubusercontent.com/39924567/224711506-846e03d4-6dbf-42f9-9381-3cdaaa5c9ed4.png)

> The axe documentation says it can be passed in as objects or css selectors

Yes, but how this plugin is written, it does not allow anything apart from string to be passed, since it relies on the output from `document.querySelector()` DOM method.

**Comment by reallymello** [comment]
Ok will take a look
